/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JProgressBar;

/**
 *
 * @author ariel
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    public JProgressBar getBarraprogre() {
        return Barraprogre;
    }

    public JDesktopPane getjDesktopPane1() {
        return Dskprincipal;
    }

    public JMenuItem getMenuclientes() {
        return menuclientes;
    }

    public JButton getToolbarclie() {
        return toolbarclie;
    }

    public JDesktopPane getDskprincipal() {
        return Dskprincipal;
    }

    public JMenu getMenupro() {
        return menupro;
    }

    public JMenuItem getMenuproductos() {
        return menuproductos;
    }

    public JMenuItem getMenuFacturar() {
        return menuFacturar;
    }

    public JButton getBTNFACTURAS() {
        return BTNFACTURAS;
    }

    public JButton getBOTONPRODUC() {
        return BOTONPRODUC;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        BOTONPRODUC = new javax.swing.JButton();
        BTNFACTURAS = new javax.swing.JButton();
        toolbarclie = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Barraprogre = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        Dskprincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menupro = new javax.swing.JMenu();
        menuproductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuFacturar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuclientes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(0, 102, 255));
        jToolBar1.setRollover(true);

        BOTONPRODUC.setBackground(new java.awt.Color(0, 102, 255));
        BOTONPRODUC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/paquete (1).png"))); // NOI18N
        BOTONPRODUC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BOTONPRODUC.setFocusable(false);
        BOTONPRODUC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BOTONPRODUC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BOTONPRODUC);

        BTNFACTURAS.setBackground(new java.awt.Color(0, 102, 255));
        BTNFACTURAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/lista-de-verificacion.png"))); // NOI18N
        BTNFACTURAS.setFocusable(false);
        BTNFACTURAS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNFACTURAS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTNFACTURAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNFACTURASActionPerformed(evt);
            }
        });
        jToolBar1.add(BTNFACTURAS);

        toolbarclie.setBackground(new java.awt.Color(0, 102, 255));
        toolbarclie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/person (1).png"))); // NOI18N
        toolbarclie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        toolbarclie.setFocusable(false);
        toolbarclie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarclie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarclie.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                toolbarclieStateChanged(evt);
            }
        });
        toolbarclie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarclieActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarclie);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setText("Tienda 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 727, Short.MAX_VALUE)
                .addComponent(Barraprogre, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Barraprogre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Dskprincipal.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout DskprincipalLayout = new javax.swing.GroupLayout(Dskprincipal);
        Dskprincipal.setLayout(DskprincipalLayout);
        DskprincipalLayout.setHorizontalGroup(
            DskprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DskprincipalLayout.setVerticalGroup(
            DskprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        menupro.setText("Productos");
        menupro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        menuproductos.setText("MENU PRODUCTOS");
        menuproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuproductosActionPerformed(evt);
            }
        });
        menupro.add(menuproductos);

        jMenuBar1.add(menupro);

        jMenu2.setText("Facturas");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        menuFacturar.setText("MENU FACTURAS");
        menuFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFacturarActionPerformed(evt);
            }
        });
        jMenu2.add(menuFacturar);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Clientes");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        menuclientes.setText("MENU CLIENTES");
        menuclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuclientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuclientes);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Salir");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Ayuda");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Reportes");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Dskprincipal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dskprincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuclientesActionPerformed

    private void toolbarclieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarclieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolbarclieActionPerformed

    private void menuproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuproductosActionPerformed

    private void menuFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFacturarActionPerformed

    private void toolbarclieStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_toolbarclieStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_toolbarclieStateChanged

    private void BTNFACTURASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNFACTURASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNFACTURASActionPerformed
 
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONPRODUC;
    private javax.swing.JButton BTNFACTURAS;
    private javax.swing.JProgressBar Barraprogre;
    private javax.swing.JDesktopPane Dskprincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuFacturar;
    private javax.swing.JMenuItem menuclientes;
    private javax.swing.JMenu menupro;
    private javax.swing.JMenuItem menuproductos;
    private javax.swing.JButton toolbarclie;
    // End of variables declaration//GEN-END:variables
}
