/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ariel
 */
public class Vistafactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vistafactura
     */
    public Vistafactura() {
        initComponents();
    }

    public JLabel getNumfact() {
        return numfact;
    }

    public JDialog getBuscadorprod() {
        return Buscadorprod;
    }

    public JTable getT_detalles() {
        return T_detalles;
    }

    public JTable getT_prodelegir() {
        return T_prodelegir;
    }

    public JButton getAbrirlistadoprod() {
        return abrirlistadoprod;
    }

    public JButton getAnadirdeta() {
        return anadirdeta;
    }

    public JButton getBotonCrearfac() {
        return botonCrearfac;
    }

    public JButton getBotonSalir() {
        return botonSalir;
    }

    public JButton getBtnborrarbus() {
        return btnborrarbus;
    }

    public JButton getBtnbuscarpro() {
        return btnbuscarpro;
    }

    public JButton getBuscarclie() {
        return buscarclie;
    }

    public JComboBox<String> getCombobuscar() {
        return combobuscar;
    }

    public JLabel getLabelfechafac() {
        return labelfechafac;
    }

    public JButton getSalirdetalle() {
        return salirdetalle;
    }

    public JLabel getSumadetalles() {
        return sumadetalles;
    }

    public JTextField getTxtbuscarpro() {
        return txtbuscarpro;
    }

    public JTextField getTxtcedcli() {
        return txtcedcli;
    }

    public JLabel getTxtcorreo() {
        return txtcorreo;
    }

    public JLabel getTxtnombres() {
        return txtnombres;
    }

    public JButton getBtnbuscarfac() {
        return Btnbuscarfac;
    }

    public JLabel getTxttelefono() {
        return txttelefono;
    }

    public JButton getBtnEliminarfacr() {
        return BtnEliminarfacr;
    }

    public JDialog getBuscadorFact() {
        return BuscadorFact;
    }

    public JTable getTabel_detas() {
        return Tabel_detas;
    }

    public JTable getTable_enca() {
        return Table_enca;
    }

    public JButton getBtnborrarfacts() {
        return btnborrarfacts;
    }

    public JButton getBtnbuscarfacts() {
        return btnbuscarfacts;
    }

    public JComboBox<String> getCombobuscarfacts() {
        return combobuscarfacts;
    }

    public JButton getSalirbusfacts() {
        return salirbusfacts;
    }

    public JLabel getSumadetalles1() {
        return sumadetalles1;
    }

    public JTextField getTxtbuscarfacts() {
        return txtbuscarfacts;
    }

  

  

  

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscadorprod = new javax.swing.JDialog();
        combobuscar = new javax.swing.JComboBox<>();
        txtbuscarpro = new javax.swing.JTextField();
        btnbuscarpro = new javax.swing.JButton();
        btnborrarbus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        T_prodelegir = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        anadirdeta = new javax.swing.JButton();
        salirdetalle = new javax.swing.JButton();
        BuscadorFact = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        combobuscarfacts = new javax.swing.JComboBox<>();
        txtbuscarfacts = new javax.swing.JTextField();
        btnbuscarfacts = new javax.swing.JButton();
        btnborrarfacts = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_enca = new javax.swing.JTable();
        BtnEliminarfacr = new javax.swing.JButton();
        salirbusfacts = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabel_detas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        sumadetalles1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numfact = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Btnbuscarfac = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelfechafac = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcedcli = new javax.swing.JTextField();
        buscarclie = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        abrirlistadoprod = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_detalles = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        sumadetalles = new javax.swing.JLabel();
        botonCrearfac = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        txtnombres = new javax.swing.JLabel();
        txttelefono = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        Buscadorprod.setFocusTraversalPolicyProvider(true);
        Buscadorprod.setUndecorated(true);

        combobuscar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        combobuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "Codigo", "Nombre", "Categoria" }));
        combobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobuscarActionPerformed(evt);
            }
        });

        txtbuscarpro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btnbuscarpro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/lupa (1).png"))); // NOI18N
        btnbuscarpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarproActionPerformed(evt);
            }
        });

        btnborrarbus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/x (1).png"))); // NOI18N
        btnborrarbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarbusActionPerformed(evt);
            }
        });

        T_prodelegir.setBackground(new java.awt.Color(153, 204, 255));
        T_prodelegir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(T_prodelegir);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Listado de productos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        anadirdeta.setBackground(new java.awt.Color(0, 204, 51));
        anadirdeta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        anadirdeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/anadir.png"))); // NOI18N
        anadirdeta.setText("Añadir");
        anadirdeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirdetaActionPerformed(evt);
            }
        });

        salirdetalle.setBackground(new java.awt.Color(0, 204, 51));
        salirdetalle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        salirdetalle.setForeground(new java.awt.Color(255, 255, 255));
        salirdetalle.setText("SALIR");
        salirdetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirdetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscadorprodLayout = new javax.swing.GroupLayout(Buscadorprod.getContentPane());
        Buscadorprod.getContentPane().setLayout(BuscadorprodLayout);
        BuscadorprodLayout.setHorizontalGroup(
            BuscadorprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscadorprodLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(combobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtbuscarpro)
                .addGap(18, 18, 18)
                .addComponent(btnbuscarpro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnborrarbus)
                .addGap(12, 12, 12))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BuscadorprodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BuscadorprodLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(anadirdeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirdetalle)
                .addGap(93, 93, 93))
        );
        BuscadorprodLayout.setVerticalGroup(
            BuscadorprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscadorprodLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BuscadorprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnborrarbus)
                    .addComponent(btnbuscarpro)
                    .addComponent(combobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscarpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BuscadorprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anadirdeta)
                    .addComponent(salirdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BuscadorFact.setFocusTraversalPolicyProvider(true);
        BuscadorFact.setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Listado de Facturas");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        combobuscarfacts.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        combobuscarfacts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "Cedula", "Nombres", "Numero" }));

        txtbuscarfacts.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btnbuscarfacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/lupa (1).png"))); // NOI18N
        btnbuscarfacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarfactsActionPerformed(evt);
            }
        });

        btnborrarfacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/x (1).png"))); // NOI18N
        btnborrarfacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarfactsActionPerformed(evt);
            }
        });

        Table_enca.setBackground(new java.awt.Color(153, 204, 255));
        Table_enca.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Table_enca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Table_enca);

        BtnEliminarfacr.setBackground(new java.awt.Color(255, 0, 0));
        BtnEliminarfacr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnEliminarfacr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/anadir.png"))); // NOI18N
        BtnEliminarfacr.setText("ELIMINAR");
        BtnEliminarfacr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarfacrActionPerformed(evt);
            }
        });

        salirbusfacts.setBackground(new java.awt.Color(0, 204, 51));
        salirbusfacts.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        salirbusfacts.setForeground(new java.awt.Color(255, 255, 255));
        salirbusfacts.setText("SALIR");
        salirbusfacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbusfactsActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        Tabel_detas.setBackground(new java.awt.Color(153, 204, 255));
        Tabel_detas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Tabel_detas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(Tabel_detas);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Total:");

        sumadetalles1.setBackground(new java.awt.Color(51, 102, 255));
        sumadetalles1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sumadetalles1.setOpaque(true);

        javax.swing.GroupLayout BuscadorFactLayout = new javax.swing.GroupLayout(BuscadorFact.getContentPane());
        BuscadorFact.getContentPane().setLayout(BuscadorFactLayout);
        BuscadorFactLayout.setHorizontalGroup(
            BuscadorFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscadorFactLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(combobuscarfacts, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtbuscarfacts)
                .addGap(18, 18, 18)
                .addComponent(btnbuscarfacts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnborrarfacts)
                .addGap(12, 12, 12))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BuscadorFactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BuscadorFactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscadorFactLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(BtnEliminarfacr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BuscadorFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscadorFactLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(sumadetalles1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscadorFactLayout.createSequentialGroup()
                        .addComponent(salirbusfacts, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        BuscadorFactLayout.setVerticalGroup(
            BuscadorFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscadorFactLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BuscadorFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnborrarfacts)
                    .addComponent(btnbuscarfacts)
                    .addComponent(combobuscarfacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscarfacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscadorFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sumadetalles1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(BuscadorFactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEliminarfacr)
                    .addComponent(salirbusfacts, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FACTURA");

        numfact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("#");

        Btnbuscarfac.setBackground(new java.awt.Color(0, 143, 255));
        Btnbuscarfac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/lista-de-verificacion.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btnbuscarfac, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numfact, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numfact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btnbuscarfac)))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Fecha emision:");

        labelfechafac.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelfechafac.setText(".");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Identificacion:");

        txtcedcli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcedcli.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        txtcedcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedcliActionPerformed(evt);
            }
        });

        buscarclie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/lupa (1).png"))); // NOI18N
        buscarclie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buscarclie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarclieActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Razon social:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Telefono:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Correo electronico:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("DETALLE");

        abrirlistadoprod.setBackground(new java.awt.Color(0, 102, 255));
        abrirlistadoprod.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        abrirlistadoprod.setForeground(new java.awt.Color(255, 255, 255));
        abrirlistadoprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/lupa (1).png"))); // NOI18N
        abrirlistadoprod.setText("Buscar el listado de productos");
        abrirlistadoprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirlistadoprodActionPerformed(evt);
            }
        });

        T_detalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(T_detalles);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Total:");

        sumadetalles.setBackground(new java.awt.Color(51, 102, 255));
        sumadetalles.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sumadetalles.setForeground(new java.awt.Color(255, 255, 255));
        sumadetalles.setOpaque(true);

        botonCrearfac.setBackground(new java.awt.Color(0, 204, 51));
        botonCrearfac.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonCrearfac.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearfac.setText("CREAR");
        botonCrearfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearfacActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(0, 204, 51));
        botonSalir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        txtnombres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txttelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtcorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(abrirlistadoprod)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botonCrearfac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sumadetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelfechafac, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnombres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcedcli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarclie)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelfechafac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcedcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(buscarclie)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnombres))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttelefono))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(abrirlistadoprod)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sumadetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearfac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcedcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedcliActionPerformed

    private void buscarclieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarclieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarclieActionPerformed

    private void abrirlistadoprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirlistadoprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirlistadoprodActionPerformed

    private void botonCrearfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearfacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCrearfacActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirActionPerformed

    private void btnbuscarproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarproActionPerformed

    private void btnborrarbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarbusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnborrarbusActionPerformed

    private void anadirdetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirdetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anadirdetaActionPerformed

    private void salirdetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirdetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirdetalleActionPerformed

    private void btnbuscarfactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarfactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarfactsActionPerformed

    private void btnborrarfactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarfactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnborrarfactsActionPerformed

    private void BtnEliminarfacrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarfacrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarfacrActionPerformed

    private void salirbusfactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbusfactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirbusfactsActionPerformed

    private void combobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vistafactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vistafactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vistafactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vistafactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vistafactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminarfacr;
    private javax.swing.JButton Btnbuscarfac;
    private javax.swing.JDialog BuscadorFact;
    private javax.swing.JDialog Buscadorprod;
    private javax.swing.JTable T_detalles;
    private javax.swing.JTable T_prodelegir;
    private javax.swing.JTable Tabel_detas;
    private javax.swing.JTable Table_enca;
    private javax.swing.JButton abrirlistadoprod;
    private javax.swing.JButton anadirdeta;
    private javax.swing.JButton botonCrearfac;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton btnborrarbus;
    private javax.swing.JButton btnborrarfacts;
    private javax.swing.JButton btnbuscarfacts;
    private javax.swing.JButton btnbuscarpro;
    private javax.swing.JButton buscarclie;
    private javax.swing.JComboBox<String> combobuscar;
    private javax.swing.JComboBox<String> combobuscarfacts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelfechafac;
    private javax.swing.JLabel numfact;
    private javax.swing.JButton salirbusfacts;
    private javax.swing.JButton salirdetalle;
    private javax.swing.JLabel sumadetalles;
    private javax.swing.JLabel sumadetalles1;
    private javax.swing.JTextField txtbuscarfacts;
    private javax.swing.JTextField txtbuscarpro;
    private javax.swing.JTextField txtcedcli;
    private javax.swing.JLabel txtcorreo;
    private javax.swing.JLabel txtnombres;
    private javax.swing.JLabel txttelefono;
    // End of variables declaration//GEN-END:variables

    public Object getTable_pro() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
